version: '3.8'

services:
  manga-server:
    image: nginx:alpine
    container_name: mangaverse_files
    ports:
      - "8080:80"
    volumes:
      - ./library:/usr/share/nginx/html/manga:ro

  manga-api:
    image: python:3.9-slim
    container_name: mangaverse_api
    ports:
      - "5000:5000"
    volumes:
      - ./library:/library:ro
      - ./api.py:/app/api.py
    working_dir: /app
    command: sh -c "pip install flask && python api.py"

  manga-updater:
    build: .
    container_name: mangaverse_updater
    restart: unless-stopped
    volumes:
      - ./library:/library
